# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

os:
  - osx
# Disable MacOS X for now  - osx

branches:
  only:
    - master

# Email notifications
notifications:
  email:
    on_success: change
    on_failure: change
